config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'about', to: 'about#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  get '/auth/failure', to: 'omniauth_callbacks#failure'

  resource :session
  resource :registration
  resources :twitter_accounts, only: %i[index create destroy]
  resources :tweets, only: %i[index new create]
  resources :identities, only: [:destroy]

  resource :password_reset
  resource :password

  # Defines the root path route ("/")
  root 'main#index'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  # before_action :set_user_by_token, only: [:edit, :update]

  def new; end

  def create
    @user = User.find_by(email: params[:email])
    # if (@user = User.find_by(email: params[:email]))
    if @user.present?
      PasswordMailer.with(user: @user).password_reset.deliver_now
      # PasswordMailer.with(
      #   user: @user,
      #   token: @user.generate_token_for(:password_reset)
      # ).password_reset.deliver_later
      # binding.irb
    end

    redirect_to root_path, notice: 'Check your email to reset your password.'
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to new_session_path, alert: 'Your token has expired. Please try again.'
  end

  def update
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    if @user.update(password_params)
      redirect_to new_session_path, notice: 'Your password has been successfully reset, please log in.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  # def set_user_by_token
  #   @user = User.find_by_token_for(:password_reset, params[:token])
  #   redirect_to new_password_reset_path alert: "Invalid token, please try again." unless @user.present?
  # end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_path(token: params[:token]) do |form| %>
  <%= render "shared/form_errors", form: form%>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "password"  %>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/password_resets/new.html.erb
<h1>Reset your password?</h1>

<%= form_with url: password_reset_path do |form| %>

  <div class="mb-3">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control", placeholder: "person@example.ca" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>

<% end %>