config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'about', to: 'about#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  get '/auth/failure', to: 'omniauth_callbacks#failure'

  resource :session
  resource :registration
  resources :twitter_accounts, only: %i[index create destroy]
  resources :tweets, only: %i[index new create]
  resources :identities, only: [:destroy]

  resource :password_reset
  resource :password

  # Defines the root path route ("/")
  root 'main#index'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hours.from_now
  end

  def published?
    tweet_id?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: %i[show edit update destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: 'Tweet was scheduled successfully'
    else
      render :new, status: 442
    end
  end

  def show; end

  def edit; end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: 'Tweet updated successfully'
    else
      render :edit
    end
  end

  def destroy
    if @tweet.destroy
      redirect_to tweets_path, notice: 'Tweet was unscheduled'
    else
      redirect_to tweets_path, alert: 'Unable to remove schedule, please try again.'
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
  <%= render "shared/form_errors", form: form%>

  <div class="mb-3">
    <%= form.label :twitter_account_id %>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: "form-control"} %>
    <%= link_to "Connect a new account", "/auth/twitter", data:{turbo: "false"}, method: :post %>
  </div>

  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :publish_at %>
    <div class="form-control">
      <%= form.datetime_select :publish_at%>
    </div>
  </div>

  <%= form.button "Schedule", class: "btn btn-primary" %>

  <% if form.object.persisted? %>
    <%= link_to "Delete", tweet,
      data: { "turbo_method": :delete, turbo_confirm: "Are you sure?" }, 
      class: "btn btn-outline-danger"
    %>
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body" id="<%= dom_id tweet%>">
  <%= tweet.body %>
  <div class="me-4">
    <%= image_tag tweet.twitter_account.image, class: "rounded-circle" %>
    <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>
    <% if tweet.published? %>
      <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
    <%else %>
      Scheduled for: <%= l tweet.publish_at, format: :short %>
      <%= link_to "Edit Tweet", edit_tweet_path(tweet) %>
    <% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Edit scheduled tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Tweets</h1>

  <% if Current.user.twitter_accounts.any? %>
    <%= link_to "Schedule a Tweet", new_tweet_path, class: "btn btn-primary" %>
  <% end%>

</div>

<% if Current.user.twitter_accounts.none? %>
  <%= button_to "Connect a Twitter Account", "/auth/twitter", data:{turbo: "false"}, method: :post, class: "btn btn-primary" %>
<% end %>

<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule a Tweet</h1>

<%= render "form", tweet: @tweet %>