config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'about', to: 'about#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  get '/auth/failure', to: 'omniauth_callbacks#failure'

  resource :session
  resource :registration
  resources :twitter_accounts, only: %i[index create destroy]
  resources :tweets, only: %i[index new create]
  resources :identities, only: [:destroy]

  resource :password_reset
  resource :password

  # Defines the root path route ("/")
  root 'main#index'
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="text-danger alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<%  if form.object.errors.any? %>
  <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container mx-auto px-4 rounded-box">  
  <div class="navbar flex bg-base-300 rounded-lg mb-2" id="main-nav">
    <%= link_to "Mutter", root_path, class: "navbar-brand navbar-start" %>
    <ul class="navbar-nav mb-2 mb-lg-0 flex navbar-center">
      <li class="nav-item button-neutral px-2">
        <%= link_to "Home", root_path, class: "nav-link btn" %>
      </li>
      <li class="nav-item px-2">
        <%= link_to "About", about_path, class: "nav-link btn" %>
      </li>
      <li class="nav-item px-2">
        <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link btn" %>
      </li>
      <li class="nav-item px-2">
        <%= link_to "Tweets", tweets_path, class: "nav-link btn" %>
      </li>
    </ul>
    <div class="navbar-nav navbar-end flex items-center">
      <% if user_signed_in? %>
        <div class="dropdown dropdown-end">
          <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
            <div class="w-10 rounded-full">
              <img
                alt="Tailwind CSS Navbar component"
                src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp" />
            </div>
          </div>
          <ul
            tabindex="0"
            class="dropdown-content menu menu-sm bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
            <li class="X-nav-item X-px-2"><%= link_to (Current.user.username || "Profile"), edit_registration_path, class: "justify between" %></li>
            <li class="X-nav-item X-px-2"><%= link_to "Change password", edit_password_path, class: "nav-link" %></li>
            <li class="X-nav-item X-px-2"><%= button_to "Log out", session_path, method: :delete, class: "btn btn-danger"%></li>
          </ul>
        </div>
      <% else %>
        <ul class="menu menu-horizontal rounded-box">
          <li><%= link_to "Sign Up", new_registration_path, class: "nav-link" %></li>
          <li><%= link_to "Log In", new_session_path, class: "nav-link" %></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>